### ISSUE TITLE
Unable to print indented code block

### ISSUE THREAD

**Issue by esnahn** [PDConSec/vsc-print#333]
```
    a

```

When you try to print a file with a code block with 4 indentation,

```
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
	at e.processFencedBlocks (c:\Users\...\.vscode\extensions\pdconsec.vscode-print-0.12.4\dist\extension.js:2:3418561)
	at e.getBodyHtml (c:\Users\...\.vscode\extensions\pdconsec.vscode-print-0.12.4\dist\extension.js:2:3412214)
	at E.getBodyHtml (c:\Users\...\.vscode\extensions\pdconsec.vscode-print-0.12.4\dist\extension.js:2:3400844)
	at e.HtmlDocumentBuilder.build (c:\Users\...\.vscode\extensions\pdconsec.vscode-print-0.12.4\dist\extension.js:2:3408330)
	at c.respond (c:\Users\...\.vscode\extensions\pdconsec.vscode-print-0.12.4\dist\extension.js:2:3396157)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Server.<anonymous> (c:\Users\...\.vscode\extensions\pdconsec.vscode-print-0.12.4\dist\extension.js:2:3383933)
```

This error is displayed instead.

minimal test file:
[print test.md](https://github.com/user-attachments/files/16123015/print.test.md)

**Comment by PeterWone** [comment]
Oh, it will be because there's no lang specified, I'll take care of that in the emergency bugfix I'm about to release.

**Comment by PeterWone** [comment]
Get the latest and if it's working correctly please close the issue.

**Comment by esnahn** [comment]
Fixed! Thanks for the fast response.
